version: "3"
services:
  php-apache:
    image: php:7.2.1-apache
    build:
      context: ./php-apache
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    links:
      - "mariadb"

mariadb:
  image: mariadb:10.1
  restart: always
  volumes:
    - mariadb:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: kerrigan
    MYSQL_PASSWORD: Kerrigan
    MYSQL_DATABASE: zerg

volumes: mariadb:
